services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      postgres:
        condition: service_healthy
      parser: 
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  parser:
    build: 
      context: ./parser
      dockerfile: Dockerfile.dev
    container_name: parser_container
    ports:
      - "5001:5001"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:5001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    volumes:
      - ./parser:/app
      - /app/node_modules
      
  frontend:
    build: ./frontend
    restart: always
    environment:
      API_BASE: http://backend:5000
    ports:
      - '3000:3000'
    depends_on:
      backend: 
        condition: service_healthy
    networks:
    - app_network

  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
        
volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge